CREATE TABLE users(
  id INT NOT NULL AUTO_INCREMENT,
  user_name VARCHAR(50),
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(300) NOT NULL,
	user_img VARCHAR(3000),
  created_at DATETIME DEFAULT NOW(),
  updated_at DATETIME,
  PRIMARY KEY (id)
);