CREATE TABLE classes (
	id int NOT NULL auto_increment,
    class_name VARCHAR(100)not null,
    instructor_id int not null,
    price float,
    discounted_price float DEFAULT NULL, 
    img varchar(1000),
    rate float,
    description text,
    students int,
    sessions int,
    category1_id int,
    category2_id int,
    category3_id int,
    level_id int,
    created_at DATETIME DEFAULT NOW(),
    updated_at DATETIME,
    PRIMARY KEY(id),
    FOREIGN KEY(category1_id)references category(id),
    FOREIGN KEY(category2_id)references category(id),
    FOREIGN KEY(category3_id)references category(id),
    FOREIGN KEY(level_id)references level(id),
    FOREIGN KEY(instructor_id)references instructor(id)
)